In [1]:
import pandas as pd
import requests

In [ ]:
# Fetching earthquake data from the USGS API
url = "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson"
response = requests.get(url)
data = response.json()

In [10]:
#Display the keys of API through which we can access
print(data.keys())

dict_keys(['type', 'metadata', 'features', 'bbox'])

In [ ]:
#To view the single value of earthquake
single_earthquake = data["features"][0]
single_earthquake

{'type': 'Feature',
 'properties': {'mag': 1.53,
  'place': '34 km SW of Independence, CA',
  'time': 1789879702060,
  'updated': 1789879911228,
  'tz': None,
  'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ci41335375',
  'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci41335375.geojson',
  'felt': None,
  'cdi': None,
  'mmi': None,
  'alert': None,
  'status': 'automatic',
  'tsunami': 0,
  'sig': 36,
  'net': 'ci',
  'code': '41335375',
  'ids': ',ci41335375,',
  'sources': ',ci,',
  'types': ',nearby-cities,origin,phase-data,scitech-link,',
  'nst': 9,
  'dmin': 0.4651,
  'rms': 0.16,
  'gap': 318,
  'magType': 'ml',
  'type': 'earthquake',
  'title': 'M 1.5 - 34 km SW of Independence, CA'},
 'geometry': {'type': 'Point', 'coordinates': [-118.4765, 36.599, 8.19]},
 'id': 'ci41335375'}

In [ ]:
#To access Multiple values
earthquakes = data["features"]
view = pd.json_normalize(earthquakes)
view

,type,id,properties.mag,properties.place,properties.time,properties.updated,properties.tz,properties.url,properties.detail,properties.felt,...,properties.types,properties.nst,properties.dmin,properties.rms,properties.gap,properties.magType,properties.type,properties.title,geometry.type,geometry.coordinates
0,Feature,ci41335375,1.530000,"34 km SW of Independence, CA",1789879702060,1789879911228,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,scitech-link,",9,0.465100,0.160000,318.000000,ml,earthquake,"M 1.5 - 34 km SW of Independence, CA",Point,"[-118.4765, 36.599, 8.19]"
1,Feature,nc75438772,2.270000,"10 km SW of Toms Place, CA",1789879685160,1789880243497,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,1.0,...,",dyfi,focal-mechanism,nearby-cities,origin,pha...",23,0.150500,0.080000,92.000000,md,earthquake,"M 2.3 - 10 km SW of Toms Place, CA",Point,"[-118.759834289551, 37.4921684265137, 4.480000..."
2,Feature,ci41335367,0.810000,"16 km W of Searles Valley, CA",1789879349200,1789879547846,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,",21,0.157100,0.140000,55.000000,ml,earthquake,"M 0.8 - 16 km W of Searles Valley, CA",Point,"[-117.581833333333, 35.7555, 3.8]"
3,Feature,aka2026sqgyfq,2.300000,"22 km E of Beluga, Alaska",1789878963486,1789879572081,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,1.0,...,",dyfi,origin,phase-data,",58,0.200000,0.800000,41.000000,ml,earthquake,"M 2.3 - 22 km E of Beluga, Alaska",Point,"[-150.669, 61.181, 57.3]"
4,Feature,aka2026sqgrtn,1.000000,"38 km E of Minto, Alaska",1789878513392,1789878578586,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",6,0.200000,0.100000,217.000000,ml,earthquake,"M 1.0 - 38 km E of Minto, Alaska",Point,"[-148.53, 65.152, 10]"
5,Feature,tx2026sngzur,3.000000,"56 km S of Whites City, New Mexico",1789878220140,1789879039844,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",22,0.100000,0.200000,69.000000,ml,earthquake,"M 3.0 - 56 km S of Whites City, New Mexico",Point,"[-104.364, 31.669, 7.3816]"
6,Feature,tx2026sngvai,1.600000,"59 km S of Whites City, New Mexico",1789877886984,1789878191415,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",16,0.100000,0.300000,101.000000,ml,earthquake,"M 1.6 - 59 km S of Whites City, New Mexico",Point,"[-104.368, 31.639, 4.9553]"
7,Feature,aka2026sqfocu,1.500000,"15 km WSW of Valdez, Alaska",1789876462063,1789876552733,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",7,0.100000,0.200000,163.000000,ml,earthquake,"M 1.5 - 15 km WSW of Valdez, Alaska",Point,"[-146.599, 61.06, 22.2]"
8,Feature,us7000tinl,5.300000,"108 km ESE of Yigo Village, Guam",1789875804649,1789879409789,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",event-sequence,oaf,origin,phase-data,",50,2.164000,0.670000,107.000000,mb,earthquake,"M 5.3 - 108 km ESE of Yigo Village, Guam",Point,"[145.7591, 13.0568, 10]"
9,Feature,aka2026sqeovj,2.600000,"55 km W of Anchor Point, Alaska",1789874728282,1789875504040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",105,0.200000,0.700000,66.000000,ml,earthquake,"M 2.6 - 55 km W of Anchor Point, Alaska",Point,"[-152.802, 59.713, 98.9]"
10,Feature,aka2026sqdzzi,1.800000,"19 km SW of Susitna, Alaska",1789873685063,1789873788348,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",24,0.500000,0.500000,100.000000,ml,earthquake,"M 1.8 - 19 km SW of Susitna, Alaska",Point,"[-150.764, 61.422, 65.9]"
11,Feature,nc75438762,1.220000,"8 km W of Cobb, CA",1789872933940,1789878142267,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,scitech-link,",19,0.008812,0.010000,53.000000,md,earthquake,"M 1.2 - 8 km W of Cobb, CA",Point,"[-122.811332702637, 38.8321647644043, 1.950000..."
12,Feature,nc75438752,1.050000,"8 km NW of The Geysers, CA",1789872724610,1789874545845,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,scitech-link,",22,0.007969,0.030000,49.000000,md,earthquake,"M 1.1 - 8 km NW of The Geysers, CA",Point,"[-122.813163757324, 38.8310012817383, 1.509999..."
13,Feature,us7000tinf,4.500000,"54 km ENE of Sainte-Marie, Martinique",1789872261022,1789875605425,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,2.0,...,",dyfi,moment-tensor,origin,phase-data,",61,1.143000,1.240000,108.000000,mwr,earthquake,"M 4.5 - 54 km ENE of Sainte-Marie, Martinique",Point,"[-60.5578, 15.0395, 46.424]"
14,Feature,pr71533373,2.950000,"58 km N of Culebra, Puerto Rico",1789872143580,1789878074020,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",4,0.521400,0.250000,291.000000,md,earthquake,"M 3.0 - 58 km N of Culebra, Puerto Rico",Point,"[-65.2783333333333, 18.8316666666667, 19.95]"
15,Feature,nc75438742,0.720000,"8 km NW of The Geysers, CA",1789871588390,1789873042691,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,scitech-link,",15,0.008711,0.010000,63.000000,md,earthquake,"M 0.7 - 8 km NW of The Geysers, CA",Point,"[-122.816833496094, 38.8303337097168, 1.700000..."
16,Feature,pr71533328,3.120000,"75 km N of Brenas, Puerto Rico",1789871518550,1789874843940,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",13,0.830300,0.300000,266.000000,md,earthquake,"M 3.1 - 75 km N of Brenas, Puerto Rico",Point,"[-66.2716666666667, 19.149, 10.5]"
17,Feature,hv75040502,1.950000,"13 km SE of Pāhala, Hawaii",1789871323140,1789871524740,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",29,0.082310,0.180000,227.000000,md,earthquake,"M 2.0 - 13 km SE of Pāhala, Hawaii",Point,"[-155.380340576172, 19.1270008087158, 28.14999..."
18,Feature,hv75040492,2.250000,"5 km SSW of Volcano, Hawaii",1789870647420,1789870864670,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",27,0.007784,0.190000,49.000000,ml,earthquake,"M 2.3 - 5 km SSW of Volcano, Hawaii",Point,"[-155.251495361328, 19.3933334350586, 1.450000..."
19,Feature,pr71533323,2.010000,"4 km SW of Guánica, Puerto Rico",1789869851750,1789871899900,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",8,0.036790,0.140000,215.000000,md,earthquake,"M 2.0 - 4 km SW of Guánica, Puerto Rico",Point,"[-66.9348333333333, 17.945, 9.27]"
20,Feature,aka2026sqbrhg,2.600000,"33 km NW of Nanwalek, Alaska",1789869485292,1789870051040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",78,0.400000,0.700000,88.000000,ml,earthquake,"M 2.6 - 33 km NW of Nanwalek, Alaska",Point,"[-152.368, 59.556, 68.1]"
21,Feature,ci41335335,0.650000,"4 km NNW of Anza, CA",1789869216010,1789869418352,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,",45,0.044360,0.210000,44.000000,ml,earthquake,"M 0.7 - 4 km NNW of Anza, CA",Point,"[-116.691833333333, 33.5883333333333, 1.97]"
22,Feature,nc75438732,0.350000,"2 km NW of The Geysers, CA",1789868252490,1789870040361,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,scitech-link,",6,0.014890,0.000000,102.000000,md,earthquake,"M 0.4 - 2 km NW of The Geysers, CA",Point,"[-122.769500732422, 38.7878341674805, 1.700000..."
23,Feature,aka2026sqaogn,1.300000,"32 km NNW of Valdez, Alaska",1789867476539,1789867540013,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",10,0.400000,0.600000,106.000000,ml,earthquake,"M 1.3 - 32 km NNW of Valdez, Alaska",Point,"[-146.67, 61.378, 31.8]"
24,Feature,aka2026sqagtb,1.000000,"92 km N of Karluk, Alaska",1789866955716,1789866999055,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",8,0.100000,0.300000,204.000000,ml,earthquake,"M 1.0 - 92 km N of Karluk, Alaska",Point,"[-154.481, 58.402, 5.8]"
25,Feature,aka2026sqaftm,1.200000,"92 km N of Karluk, Alaska",1789866887493,1789866929451,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",12,0.100000,0.300000,209.000000,ml,earthquake,"M 1.2 - 92 km N of Karluk, Alaska",Point,"[-154.465, 58.396, 7.2]"
26,Feature,aka2026sqadtu,2.600000,"90 km N of Karluk, Alaska",1789866750465,1789867706040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",52,0.100000,0.700000,76.000000,ml,earthquake,"M 2.6 - 90 km N of Karluk, Alaska",Point,"[-154.484, 58.382, 5]"
27,Feature,aka2026spzvej,1.500000,"24 km SE of Chickaloon, Alaska",1789866155519,1789866217921,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",7,0.200000,0.200000,84.000000,ml,earthquake,"M 1.5 - 24 km SE of Chickaloon, Alaska",Point,"[-148.127, 61.648, 18.5]"
28,Feature,us7000timy,5.300000,Reykjanes Ridge,1789865894425,1789866820040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",moment-tensor,origin,phase-data,",77,8.549000,1.250000,66.000000,mww,earthquake,M 5.3 - Reykjanes Ridge,Point,"[-33.5459, 57.1211, 10]"
29,Feature,aka2026spzqva,1.700000,"88 km ESE of Ugashik, Alaska",1789865853332,1789865929466,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",8,0.400000,0.700000,261.000000,ml,earthquake,"M 1.7 - 88 km ESE of Ugashik, Alaska",Point,"[-156.019, 57.235, 11.4]"
30,Feature,nc75438722,1.460000,"11 km ESE of New Idria, CA",1789865753770,1789873043691,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,scitech-link,",4,0.165200,0.210000,184.000000,md,earthquake,"M 1.5 - 11 km ESE of New Idria, CA",Point,"[-120.556831359863, 36.3828315734863, 3.839999..."
31,Feature,nc75438707,0.730000,"3 km NW of The Geysers, CA",1789865221610,1789866742979,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,scitech-link,",8,0.012800,0.020000,78.000000,md,earthquake,"M 0.7 - 3 km NW of The Geysers, CA",Point,"[-122.78116607666, 38.8014984130859, 3.9300000..."
32,Feature,tx2026smzort,1.700000,"40 km ESE of Malaga, New Mexico",1789864956379,1789867660484,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",19,0.100000,0.400000,94.000000,ml,earthquake,"M 1.7 - 40 km ESE of Malaga, New Mexico",Point,"[-103.679, 32.071, 8.106]"
33,Feature,aka2026spyyke,0.800000,"86 km NNW of Karluk, Alaska",1789864583747,1789864673443,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",9,0.000000,0.300000,135.000000,ml,earthquake,"M 0.8 - 86 km NNW of Karluk, Alaska",Point,"[-154.972, 58.295, 5]"
34,Feature,aka2026spyyci,2.300000,"15 km N of Chickaloon, Alaska",1789864558206,1789866922720,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,1.0,...,",dyfi,origin,phase-data,",52,0.500000,0.800000,30.000000,ml,earthquake,"M 2.3 - 15 km N of Chickaloon, Alaska",Point,"[-148.508, 61.937, 7.4]"
35,Feature,us7000timw,4.900000,"85 km W of Hihifo, Tonga",1789864401417,1789866327040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",21,3.400000,1.270000,68.000000,mb,earthquake,"M 4.9 - 85 km W of Hihifo, Tonga",Point,"[-174.5971, -15.9606, 10]"
36,Feature,nc75438697,1.470000,"4 km SE of Aromas, CA",1789863993840,1789870041361,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,scitech-link,",19,0.029920,0.220000,95.000000,md,earthquake,"M 1.5 - 4 km SE of Aromas, CA",Point,"[-121.611335754395, 36.8588333129883, 7]"
37,Feature,hv75040452,2.350000,"5 km S of Pāhala, Hawaii",1789863559090,1789863772170,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",41,0.022920,0.210000,128.000000,ml,earthquake,"M 2.4 - 5 km S of Pāhala, Hawaii",Point,"[-155.48616027832, 19.158332824707, 12.9700002..."
38,Feature,nc75438677,2.110000,"2 km NE of Pacifica, CA",1789863369740,1789874410556,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,8.0,...,",dyfi,focal-mechanism,nearby-cities,origin,pha...",42,0.011100,0.050000,68.000000,md,earthquake,"M 2.1 - 2 km NE of Pacifica, CA",Point,"[-122.471832275391, 37.626335144043, 6.5700001..."
39,Feature,pr71533288,2.520000,"3 km WSW of Fuig, Puerto Rico",1789863232310,1789864205150,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",13,0.039240,0.240000,176.000000,md,earthquake,"M 2.5 - 3 km WSW of Fuig, Puerto Rico",Point,"[-66.9498333333333, 17.9738333333333, 6.91]"
40,Feature,aka2026spxztd,1.300000,"19 km N of Four Mile Road, Alaska",1789862873728,1789863100341,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",17,0.200000,0.600000,57.000000,ml,earthquake,"M 1.3 - 19 km N of Four Mile Road, Alaska",Point,"[-149.178, 64.778, 16.1]"
41,Feature,nc75438672,1.530000,"4 km N of Aromas, CA",1789862644360,1789867341044,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,scitech-link,",19,0.013510,0.070000,72.000000,md,earthquake,"M 1.5 - 4 km N of Aromas, CA",Point,"[-121.647499084473, 36.9238319396973, 3.970000..."
42,Feature,us7000timl,4.200000,"116 km NNE of Lospalos, Timor Leste",1789862046577,1789871929040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",30,6.309000,0.880000,117.000000,mb,earthquake,"M 4.2 - 116 km NNE of Lospalos, Timor Leste",Point,"[127.5122, -7.6037, 152.595]"
43,Feature,nc75438667,1.620000,"13 km SE of Markleeville, CA",1789861782100,1789865542832,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,scitech-link,",6,0.125300,0.070000,125.000000,md,earthquake,"M 1.6 - 13 km SE of Markleeville, CA",Point,"[-119.677833557129, 38.613166809082, 2.3599998..."
44,Feature,ci41335319,0.950000,"15 km E of Coso Junction, CA",1789861486430,1789861698466,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,",25,0.013390,0.190000,51.000000,ml,earthquake,"M 1.0 - 15 km E of Coso Junction, CA",Point,"[-117.780166666667, 36.031, 1.56]"
45,Feature,aka2026spwuzl,1.000000,"92 km N of Karluk, Alaska",1789860744732,1789860793982,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",11,0.100000,0.300000,206.000000,ml,earthquake,"M 1.0 - 92 km N of Karluk, Alaska",Point,"[-154.47, 58.403, 4.1]"
46,Feature,nc75438647,1.030000,"7 km NW of The Geysers, CA",1789860276250,1789862242471,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,scitech-link,",20,0.007734,0.020000,49.000000,md,earthquake,"M 1.0 - 7 km NW of The Geysers, CA",Point,"[-122.801002502441, 38.8264999389648, 1.779999..."
47,Feature,us7000timg,4.200000,"24 km S of Sipí, Colombia",1789860015368,1789873363040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",21,2.058000,1.250000,94.000000,mb,earthquake,"M 4.2 - 24 km S of Sipí, Colombia",Point,"[-76.628, 4.436, 80.206]"
48,Feature,aka2026spwcaz,1.000000,"7 km E of Fox, Alaska",1789859434785,1789859493242,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",11,0.200000,0.800000,55.000000,ml,earthquake,"M 1.0 - 7 km E of Fox, Alaska",Point,"[-147.468, 64.96, 5]"
49,Feature,aka2026spvyab,0.800000,"88 km N of Karluk, Alaska",1789859156217,1789859328711,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",5,0.100000,0.100000,262.000000,ml,earthquake,"M 0.8 - 88 km N of Karluk, Alaska",Point,"[-154.483, 58.359, 5.9]"
50,Feature,tx2026smwldq,1.700000,"61 km S of Whites City, New Mexico",1789859116326,1789861821015,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",19,0.100000,0.300000,75.000000,ml,earthquake,"M 1.7 - 61 km S of Whites City, New Mexico",Point,"[-104.461, 31.626, 3.656]"
51,Feature,pr71533238,2.320000,"4 km WSW of Fuig, Puerto Rico",1789858827860,1789859936370,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",13,0.049510,0.240000,163.000000,md,earthquake,"M 2.3 - 4 km WSW of Fuig, Puerto Rico",Point,"[-66.9603333333333, 17.9778333333333, 7.61]"
52,Feature,tx2026smwdrk,2.700000,"15 km SSW of Smiley, Texas",1789858574262,1789876202738,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,1.0,...,",dyfi,origin,phase-data,",18,0.100000,0.200000,73.000000,ml,earthquake,"M 2.7 - 15 km SSW of Smiley, Texas",Point,"[-97.682, 29.137, 9.6561]"
53,Feature,nc75438632,2.000000,"21 km NW of Parkfield, CA",1789858467340,1789860443256,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",focal-mechanism,nearby-cities,origin,phase-da...",30,0.031830,0.070000,49.000000,md,earthquake,"M 2.0 - 21 km NW of Parkfield, CA",Point,"[-120.593170166016, 36.0369987487793, 7.030000..."

In [16]:
# Viewing the cleaned data According to the features 
clean_view=view[['properties.place' , 'properties.time']]
clean_view

                                 properties.place  properties.time
0                    34 km SW of Independence, CA    1789879702060
1                      10 km SW of Toms Place, CA    1789879685160
2                   16 km W of Searles Valley, CA    1789879349200
3                       22 km E of Beluga, Alaska    1789878963486
4                        38 km E of Minto, Alaska    1789878513392
5              56 km S of Whites City, New Mexico    1789878220140
6              59 km S of Whites City, New Mexico    1789877886984
7                     15 km WSW of Valdez, Alaska    1789876462063
8                108 km ESE of Yigo Village, Guam    1789875804649
9                 55 km W of Anchor Point, Alaska    1789874728282
10                    19 km SW of Susitna, Alaska    1789873685063
11                             8 km W of Cobb, CA    1789872933940
12                     8 km NW of The Geysers, CA    1789872724610
13          54 km ENE of Sainte-Marie, Martinique    1789872261022
14                58 km N of Culebra, Puerto Rico    1789872143580
15                     8 km NW of The Geysers, CA    1789871588390
16                 75 km N of Brenas, Puerto Rico    1789871518550
17                     13 km SE of Pāhala, Hawaii    1789871323140
18                    5 km SSW of Volcano, Hawaii    1789870647420
19                4 km SW of Guánica, Puerto Rico    1789869851750
20                   33 km NW of Nanwalek, Alaska    1789869485292
21                           4 km NNW of Anza, CA    1789869216010
22                     2 km NW of The Geysers, CA    1789868252490
23                    32 km NNW of Valdez, Alaska    1789867476539
24                      92 km N of Karluk, Alaska    1789866955716
25                      92 km N of Karluk, Alaska    1789866887493
26                      90 km N of Karluk, Alaska    1789866750465
27                 24 km SE of Chickaloon, Alaska    1789866155519
28                                Reykjanes Ridge    1789865894425
29                   88 km ESE of Ugashik, Alaska    1789865853332
30                     11 km ESE of New Idria, CA    1789865753770
31                     3 km NW of The Geysers, CA    1789865221610
32                40 km ESE of Malaga, New Mexico    1789864956379
33                    86 km NNW of Karluk, Alaska    1789864583747
34                  15 km N of Chickaloon, Alaska    1789864558206
35                       85 km W of Hihifo, Tonga    1789864401417
36                          4 km SE of Aromas, CA    1789863993840
37                       5 km S of Pāhala, Hawaii    1789863559090
38                        2 km NE of Pacifica, CA    1789863369740
39                  3 km WSW of Fuig, Puerto Rico    1789863232310
40              19 km N of Four Mile Road, Alaska    1789862873728
41                           4 km N of Aromas, CA    1789862644360
42            116 km NNE of Lospalos, Timor Leste    1789862046577
43                   13 km SE of Markleeville, CA    1789861782100
44                   15 km E of Coso Junction, CA    1789861486430
45                      92 km N of Karluk, Alaska    1789860744732
46                     7 km NW of The Geysers, CA    1789860276250
47                      24 km S of Sipí, Colombia    1789860015368
48                          7 km E of Fox, Alaska    1789859434785
49                      88 km N of Karluk, Alaska    1789859156217
50             61 km S of Whites City, New Mexico    1789859116326
51                  4 km WSW of Fuig, Puerto Rico    1789858827860
52                     15 km SSW of Smiley, Texas    1789858574262
53                      21 km NW of Parkfield, CA    1789858467340
54         3 km SSW of General Mosconi, Argentina    1789858416658
55                4 km SW of Guánica, Puerto Rico    1789858004600
56                      93 km N of Karluk, Alaska    1789857901635
57                           3 km WSW of Anza, CA    1789856926860
58                      0 km N of The Geysers, CA    1789856480290
59                    4 km WNW of Santa Paula, CA    1789856446550
60                  17 km ESE of Balmorhea, Texas    1789856446072
61                   4 km NNE of Yucca Valley, CA    1789856193840
62                110 km N of Suárez, Puerto Rico    1789856117580
63                      2 km N of The Geysers, CA    1789855215170
64                   41 km W of Ninilchik, Alaska    1789854943272
65                      3 km ENE of Escondido, CA    1789854358310
66                249 km N of Likisá, Timor Leste    1789854290193
67                 62 km E of Denali Park, Alaska    1789853644899
68                   3 km SSE of Bombay Beach, CA    1789853141230
69                     7 km NW of The Geysers, CA    1789852693790
70                    9 km NW of Prague, Oklahoma    1789852121729
71                        37 km N of Malfa, Italy    1789851332082
72                    5 km WNW of The Geysers, CA    1789850640280
73                     2 km NW of The Geysers, CA    1789850418640
74                     2 km NNW of Pāhala, Hawaii    1789850298200
75                                Reykjanes Ridge    1789849482449
76                     5 km SW of Volcano, Hawaii    1789849253000
77                     5 km SW of Volcano, Hawaii    1789849252420
78                  69 km SSW of Kaktovik, Alaska    1789849242592
79                    66 km WNW of Tyonek, Alaska    1789849122951
80                      4 km ENE of Escondido, CA    1789848687260
81                      8 km SSW of Idyllwild, CA    1789848444450
82                18 km SSW of Searles Valley, CA    1789848055920
83              12 km SE of Emajagua, Puerto Rico    1789847789150
84                        22 km SSW of Manton, CA    1789847571470
85                        3 km SSE of Compton, CA    1789846601430
86                5 km SW of Guánica, Puerto Rico    1789846389380
87                  4 km WSW of Fuig, Puerto Rico    1789846284490
88                49 km W of Anchor Point, Alaska    1789846131863
89                     4 km NW of The Geysers, CA    1789845893920
90      11 km SSE of Denali National Park, Alaska    1789845497223
91                   39 km E of Pedro Bay, Alaska    1789845086198
92                  128 km SE of McCarthy, Alaska    1789844016834
93                     7 km NW of The Geysers, CA    1789843899400
94                          10 km NNW of Anza, CA    1789843794220
95                       47 km NW of Toyah, Texas    1789843548752
96   1 km S of Liborio Negron Torres, Puerto Rico    1789842782280
97                   20 km ESE of Naalehu, Hawaii    1789842384370
98                     2 km NW of The Geysers, CA    1789841979400
99                    2 km NNW of The Geysers, CA    1789840116280
100              4 km WSW of Guánica, Puerto Rico    1789840015820
101                   84 km WSW of Karluk, Alaska    1789838892378
102                  30 km E of Kelso, Washington    1789838388250
103          11 km N of Quebradillas, Puerto Rico    1789838317940
104              7 km SSW of Guánica, Puerto Rico    1789838185000
105                  20 km ESE of Little Lake, CA    1789838159700
106                      16 km NW of Freer, Texas    1789837780672
107              3 km WNW of Anderson Springs, CA    1789837366280
108                    22 km SSW of La Quinta, CA    1789836924890
109                   3 km W of Fuig, Puerto Rico    1789836651150
110                   78 km NNW of Karluk, Alaska    1789835995747
111                  2 km SW of Fuig, Puerto Rico    1789835479480
112                          7 km WNW of Cobb, CA    1789834997860
113                            4 km W of Cobb, CA    1789834387950
114                  11 km E of Ninilchik, Alaska    1789833346538
115                       75 km SE of Kuqa, China    1789833234494
116                    8 km ESE of Cloverdale, CA    1789831866260
117                    34 km N of Chenega, Alaska    1789831656882
118                          4 km WSW of Anza, CA    1789831546490
119                      4 km S of Pāhala, Hawaii    1789831496820
120                  87 km SSE of Igiugig, Alaska    1789830276775
121                   72 km WNW of Tyonek, Alaska    1789829507140
122                   4 km W of Fuig, Puerto Rico    1789829241520
123                   50 km SSE of Tanana, Alaska    1789828042321
124                     13 km NE of Hollister, CA    1789827677100
125                            8 km W of Cobb, CA    1789827653530
126                    7 km NW of The Geysers, CA    1789827540810
127                  14 km SE of Markleeville, CA    1789826829530
128                    3 km NNW of Stanton, Texas    1789826808234
129                     22 km SW of La Quinta, CA    1789826706550
130                         21 km ESE of Anza, CA    1789826388020
131             6 km SSW of Trapper Creek, Alaska    1789826337695
132                 67 km NE of Ruteng, Indonesia    1789826160869
133                   29 km WSW of Sipí, Colombia    1789825475732
134                 2 km WNW of Fuig, Puerto Rico    1789824661090
135               21 km W of Anchor Point, Alaska    1789824516602
136              4 km WSW of Guánica, Puerto Rico    1789824306030
137                   34 km NW of Coquimbo, Chile    1789824303351
138                   14 km ENE of Pāhala, Hawaii    1789824298820
139                 57 km SE of Pedro Bay, Alaska    1789824130124
140                         1 km NE of Julian, CA    1789822684000
141                2 km W of Guánica, Puerto Rico    1789822173660
142                 85 km SSW of Nikolski, Alaska    1789821843347
143          58 km SSW of Whites City, New Mexico    1789820792727
144                         4 km N of Banning, CA    1789820432990
145                    273 km NNW of Dêqên, China    1789820395048
146                   12 km ESE of Kodiak, Alaska    1789819907293
147              25 km NW of Ushibukamachi, Japan    1789819632020
148                          3 km W of Dublin, CA    1789819596690
149                        4 km WNW of Dublin, CA    1789819564060
150                          6 km WNW of Cobb, CA    1789819043600
151                65 km ENE of Pedro Bay, Alaska    1789818969162
152                    8 km NW of The Geysers, CA    1789818834270
153                          7 km WNW of Cobb, CA    1789818818790
154                     15 km W of Karluk, Alaska    1789818814277
155                          7 km WNW of Cobb, CA    1789818791770
156                     94 km N of Karluk, Alaska    1789818696787
157                   9 km WNW of The Geysers, CA    1789818544580
158                   27 km NNE of Karluk, Alaska    1789818219653
159                    6 km NW of The Geysers, CA    1789818194740
160                      45 km NW of Toyah, Texas    1789817609667
161                   12 km SSE of Stanton, Texas    1789817020378
162                   21 km NNW of Karluk, Alaska    1789816722617
163                 6 km WSW of Fuig, Puerto Rico    1789816681240
164                  8 km E of Ridgely, Tennessee    1789816327700
165                    8 km NW of The Geysers, CA    1789816078090
166                     9 km WSW of Idyllwild, CA    1789815765120
167                   47 km WSW of Karluk, Alaska    1789815703637
168                 4 km WSW of Fuig, Puerto Rico    1789815241810
169                     10 km ENE of Milpitas, CA    1789815125170
170                          8 km WNW of Cobb, CA    1789815094700
171                  3 km SW of Fuig, Puerto Rico    1789815001870
172                   5 km NNW of Morgan Hill, CA    1789814990770
173                 4 km WSW of Fuig, Puerto Rico    1789814021320
174                    18 km SW of Mongar, Bhutan    1789813877071
175                   9 km WNW of The Geysers, CA    1789813432190
176                   2 km NNE of The Geysers, CA    1789812773880
177                    20 km W of Coyanosa, Texas    1789812373641
178                 South Sandwich Islands region    1789811999264
179                   67 km WNW of Karluk, Alaska    1789811899197
180                      4 km NE of Límni, Greece    1789811762046
181              4 km WSW of Guánica, Puerto Rico    1789810864800
182                 61 km WNW of Nanwalek, Alaska    1789810525226
183                268 km NNW of Kuril’sk, Russia    1789810444394
184      50 km ESE of Pope-Vannoy Landing, Alaska    1789810409379
185                   85 km NNW of Karluk, Alaska    1789809653212
186                          7 km WNW of Cobb, CA    1789809163650
187                   80 km NNW of Karluk, Alaska    1789808918864
188                           12 km W of Anza, CA    1789808504530
189                    7 km NW of The Geysers, CA    1789808288480
190                     19 km N of San Simeon, CA    1789808093460
191           20 km SSW of South Van Horn, Alaska    1789807787349
192                 166 km SW of Nikolski, Alaska    1789807670579
193                   85 km NNW of Karluk, Alaska    1789807160798
194              5 km WSW of Guánica, Puerto Rico    1789807077070
195             27 km WNW of Anchor Point, Alaska    1789806816892
196                       23 km W of Hope, Alaska    1789804902438
197              142 km N of Hatillo, Puerto Rico    1789804462700
198                      46 km NW of Toyah, Texas    1789804444995
199                      47 km NW of Toyah, Texas    1789804389502
200                210 km W of Abepura, Indonesia    1789803865478
201          63 km SSW of Whites City, New Mexico    1789803717790
202                   51 km ENE of Kodiak, Alaska    1789803614597
203                     19 km SE of Pinnacles, CA    1789803599320
204                     38 km W of Mentone, Texas    1789803168256
205            58 km S of Whites City, New Mexico    1789803139086
206                77 km WNW of Ninilchik, Alaska    1789802546232
207               4 km SW of Guánica, Puerto Rico    1789802101550
208                   117 km NW of Barranca, Peru    1789801947058
209            60 km S of Whites City, New Mexico    1789801725595
210                    57 km ESE of Koseda, Japan    1789801703856
211               6 km ENE of Wardville, Oklahoma    1789801686211
212                           7 km NW of Anza, CA    1789801372290
213                7 km SSE of Ponce, Puerto Rico    1789801302940
214                9 km SSE of Ponce, Puerto Rico    1789801063180
215            16 km SE of Silver Springs, Nevada    1789800948514
216           29 km NNW of Chignik Lagoon, Alaska    1789800503596
217            38 km ENE of McKinney Acres, Texas    1789800281373
218                   15 km W of Johannesburg, CA    1789800066200
219                      3 km NNW of Knik, Alaska    1789799314499
220                65 km ENE of Pedro Bay, Alaska    1789799223790
221                    10 km E of Yorba Linda, CA    1789797943350
222                    23 km ENE of San Lucas, CA    1789797003400
223                2 km WNW of Garden City, Texas    1789796239235
224                 4 km WSW of Fuig, Puerto Rico    1789795879590
225                          5 km WNW of Cobb, CA    1789795271990
226                          9 km WNW of Cobb, CA    1789794672730
227         27 km NNE of Point Possession, Alaska    1789794458981
228               5 km SW of Guánica, Puerto Rico    1789794417780

In [17]:
# Viewing the first few rows of the cleaned data    
clean_view.head()

                properties.place  properties.time
0   34 km SW of Independence, CA    1789879702060
1     10 km SW of Toms Place, CA    1789879685160
2  16 km W of Searles Valley, CA    1789879349200
3      22 km E of Beluga, Alaska    1789878963486
4       38 km E of Minto, Alaska    1789878513392

In [18]:
# Viewing the last few rows of the cleaned data
clean_view.tail()

                          properties.place  properties.time
224          4 km WSW of Fuig, Puerto Rico    1789795879590
225                   5 km WNW of Cobb, CA    1789795271990
226                   9 km WNW of Cobb, CA    1789794672730
227  27 km NNE of Point Possession, Alaska    1789794458981
228        5 km SW of Guánica, Puerto Rico    1789794417780